services:
  fastapi_course_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d app_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  fastapi_course_app:
    image: fastapi_course_app
    entrypoint: ./entrypoint.sh
    build: .
    ports:
      - "8000:8000"
    depends_on:
      fastapi_course_database:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg://app_user:app_password@fastapi_course_database:5432/app_db

volumes:
  pgdata: